export const AIRPORTS: { icao: string; iata: string; name: string; city: string; country: string; lat: number; lon: number }[] = [
  { icao: "EGLL", iata: "LHR", name: "London Heathrow", city: "London", country: "United Kingdom", lat: 51.4775, lon: -0.4614 },
  { icao: "EGKK", iata: "LGW", name: "London Gatwick", city: "London", country: "United Kingdom", lat: 51.1537, lon: -0.1821 },
  { icao: "LFPG", iata: "CDG", name: "Paris Charles de Gaulle", city: "Paris", country: "France", lat: 49.0097, lon: 2.5479 },
  { icao: "LFPO", iata: "ORY", name: "Paris Orly", city: "Paris", country: "France", lat: 48.7233, lon: 2.3794 },
  { icao: "LFMN", iata: "NCE", name: "Nice Côte d'Azur", city: "Nice", country: "France", lat: 43.6584, lon: 7.2159 },
  { icao: "EHAM", iata: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands", lat: 52.3105, lon: 4.7683 },
  { icao: "EDDF", iata: "FRA", name: "Frankfurt", city: "Frankfurt", country: "Germany", lat: 50.0379, lon: 8.5622 },
  { icao: "EDDM", iata: "MUC", name: "Munich", city: "Munich", country: "Germany", lat: 48.3537, lon: 11.786 },
  { icao: "EDDB", iata: "BER", name: "Berlin Brandenburg", city: "Berlin", country: "Germany", lat: 52.3667, lon: 13.5033 },
  { icao: "EDDH", iata: "HAM", name: "Hamburg", city: "Hamburg", country: "Germany", lat: 53.6304, lon: 9.9882 },
  { icao: "LEMD", iata: "MAD", name: "Madrid Barajas", city: "Madrid", country: "Spain", lat: 40.4983, lon: -3.5676 },
  { icao: "LEBL", iata: "BCN", name: "Barcelona", city: "Barcelona", country: "Spain", lat: 41.2974, lon: 2.0833 },
  { icao: "LEPA", iata: "PMI", name: "Palma de Mallorca", city: "Palma", country: "Spain", lat: 39.5517, lon: 2.7388 },
  { icao: "LIRF", iata: "FCO", name: "Rome Fiumicino", city: "Rome", country: "Italy", lat: 41.8003, lon: 12.2389 },
  { icao: "LIMC", iata: "MXP", name: "Milan Malpensa", city: "Milan", country: "Italy", lat: 45.6306, lon: 8.7281 },
  { icao: "LSZH", iata: "ZRH", name: "Zurich", city: "Zurich", country: "Switzerland", lat: 47.4647, lon: 8.5492 },
  { icao: "LOWW", iata: "VIE", name: "Vienna", city: "Vienna", country: "Austria", lat: 48.1103, lon: 16.5697 },
  { icao: "EBBR", iata: "BRU", name: "Brussels", city: "Brussels", country: "Belgium", lat: 50.9014, lon: 4.4844 },
  { icao: "LPPT", iata: "LIS", name: "Lisbon", city: "Lisbon", country: "Portugal", lat: 38.7813, lon: -9.1359 },
  { icao: "EKCH", iata: "CPH", name: "Copenhagen", city: "Copenhagen", country: "Denmark", lat: 55.618, lon: 12.656 },
  { icao: "ESSA", iata: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden", lat: 59.6519, lon: 17.9186 },
  { icao: "ENGM", iata: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "Norway", lat: 60.1976, lon: 11.1004 },
  { icao: "EFHK", iata: "HEL", name: "Helsinki", city: "Helsinki", country: "Finland", lat: 60.3172, lon: 24.9633 },
  { icao: "EIDW", iata: "DUB", name: "Dublin", city: "Dublin", country: "Ireland", lat: 53.4213, lon: -6.2701 },
  { icao: "LKPR", iata: "PRG", name: "Prague", city: "Prague", country: "Czech Republic", lat: 50.1008, lon: 14.26 },
  { icao: "EPWA", iata: "WAW", name: "Warsaw", city: "Warsaw", country: "Poland", lat: 52.1657, lon: 20.9671 },
  { icao: "LHBP", iata: "BUD", name: "Budapest", city: "Budapest", country: "Hungary", lat: 47.4298, lon: 19.2611 },
  { icao: "LTFM", iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", lat: 41.2753, lon: 28.7519 },
  { icao: "LGAV", iata: "ATH", name: "Athens", city: "Athens", country: "Greece", lat: 37.9364, lon: 23.9445 },
  { icao: "OMDB", iata: "DXB", name: "Dubai Intl", city: "Dubai", country: "United Arab Emirates", lat: 25.2532, lon: 55.3657 },
  { icao: "OMAA", iata: "AUH", name: "Abu Dhabi", city: "Abu Dhabi", country: "United Arab Emirates", lat: 24.433, lon: 54.6511 },
  { icao: "OTHH", iata: "DOH", name: "Doha Hamad", city: "Doha", country: "Qatar", lat: 25.2731, lon: 51.608 },
  { icao: "OERK", iata: "RUH", name: "Riyadh King Khalid", city: "Riyadh", country: "Saudi Arabia", lat: 24.9576, lon: 46.6988 },
  { icao: "OEJN", iata: "JED", name: "Jeddah King Abdulaziz", city: "Jeddah", country: "Saudi Arabia", lat: 21.6796, lon: 39.1565 },
  { icao: "OKBK", iata: "KWI", name: "Kuwait City", city: "Kuwait City", country: "Kuwait", lat: 29.2267, lon: 47.9689 },
  { icao: "OBBI", iata: "BAH", name: "Bahrain", city: "Manama", country: "Bahrain", lat: 26.2708, lon: 50.6336 },
  { icao: "OOMS", iata: "MCT", name: "Muscat", city: "Muscat", country: "Oman", lat: 23.5933, lon: 58.2844 },
  { icao: "LLBG", iata: "TLV", name: "Tel Aviv Ben Gurion", city: "Tel Aviv", country: "Israel", lat: 32.0114, lon: 34.8867 },
  { icao: "OJAI", iata: "AMM", name: "Amman Queen Alia", city: "Amman", country: "Jordan", lat: 31.7226, lon: 35.9932 },
  { icao: "OLBA", iata: "BEY", name: "Beirut Rafic Hariri", city: "Beirut", country: "Lebanon", lat: 33.8209, lon: 35.4884 },
  { icao: "VHHH", iata: "HKG", name: "Hong Kong Intl", city: "Hong Kong", country: "Hong Kong", lat: 22.308, lon: 113.9185 },
  { icao: "WSSS", iata: "SIN", name: "Singapore Changi", city: "Singapore", country: "Singapore", lat: 1.3644, lon: 103.9915 },
  { icao: "RJTT", iata: "HND", name: "Tokyo Haneda", city: "Tokyo", country: "Japan", lat: 35.5494, lon: 139.7798 },
  { icao: "RJAA", iata: "NRT", name: "Tokyo Narita", city: "Tokyo", country: "Japan", lat: 35.7647, lon: 140.3864 },
  { icao: "RJBB", iata: "KIX", name: "Osaka Kansai", city: "Osaka", country: "Japan", lat: 34.4347, lon: 135.244 },
  { icao: "RKSI", iata: "ICN", name: "Seoul Incheon", city: "Seoul", country: "South Korea", lat: 37.4602, lon: 126.4407 },
  { icao: "ZBAA", iata: "PEK", name: "Beijing Capital", city: "Beijing", country: "China", lat: 40.0801, lon: 116.5846 },
  { icao: "ZBAD", iata: "PKX", name: "Beijing Daxing", city: "Beijing", country: "China", lat: 39.5098, lon: 116.4105 },
  { icao: "ZSPD", iata: "PVG", name: "Shanghai Pudong", city: "Shanghai", country: "China", lat: 31.1443, lon: 121.8083 },
  { icao: "ZSSS", iata: "SHA", name: "Shanghai Hongqiao", city: "Shanghai", country: "China", lat: 31.1979, lon: 121.3363 },
  { icao: "ZGGG", iata: "CAN", name: "Guangzhou Baiyun", city: "Guangzhou", country: "China", lat: 23.3924, lon: 113.2988 },
  { icao: "ZGSZ", iata: "SZX", name: "Shenzhen Bao'an", city: "Shenzhen", country: "China", lat: 22.6393, lon: 113.8107 },
  { icao: "ZPPP", iata: "KMG", name: "Kunming Changshui", city: "Kunming", country: "China", lat: 25.1019, lon: 102.9293 },
  { icao: "VTBS", iata: "BKK", name: "Bangkok Suvarnabhumi", city: "Bangkok", country: "Thailand", lat: 13.69, lon: 100.7501 },
  { icao: "VTBD", iata: "DMK", name: "Bangkok Don Mueang", city: "Bangkok", country: "Thailand", lat: 13.9126, lon: 100.6068 },
  { icao: "WMKK", iata: "KUL", name: "Kuala Lumpur", city: "Kuala Lumpur", country: "Malaysia", lat: 2.7456, lon: 101.7099 },
  { icao: "WIII", iata: "CGK", name: "Jakarta Soekarno-Hatta", city: "Jakarta", country: "Indonesia", lat: -6.1256, lon: 106.6559 },
  { icao: "RPLL", iata: "MNL", name: "Manila Ninoy Aquino", city: "Manila", country: "Philippines", lat: 14.5086, lon: 121.0194 },
  { icao: "RCTP", iata: "TPE", name: "Taipei Taoyuan", city: "Taipei", country: "Taiwan", lat: 25.0777, lon: 121.2328 },
  { icao: "VVNB", iata: "HAN", name: "Hanoi Noi Bai", city: "Hanoi", country: "Vietnam", lat: 21.2212, lon: 105.8072 },
  { icao: "VVTS", iata: "SGN", name: "Ho Chi Minh City", city: "Ho Chi Minh City", country: "Vietnam", lat: 10.8188, lon: 106.652 },
  { icao: "VIDP", iata: "DEL", name: "Delhi Indira Gandhi", city: "Delhi", country: "India", lat: 28.5562, lon: 77.1 },
  { icao: "VABB", iata: "BOM", name: "Mumbai Chhatrapati Shivaji", city: "Mumbai", country: "India", lat: 19.0887, lon: 72.8679 },
  { icao: "VOBL", iata: "BLR", name: "Bangalore Kempegowda", city: "Bangalore", country: "India", lat: 13.1986, lon: 77.7066 },
  { icao: "VOMM", iata: "MAA", name: "Chennai", city: "Chennai", country: "India", lat: 12.9941, lon: 80.1709 },
  { icao: "VECC", iata: "CCU", name: "Kolkata", city: "Kolkata", country: "India", lat: 22.6547, lon: 88.4467 },
  { icao: "VOHS", iata: "HYD", name: "Hyderabad Rajiv Gandhi", city: "Hyderabad", country: "India", lat: 17.2403, lon: 78.4294 },
  { icao: "VNKT", iata: "KTM", name: "Kathmandu Tribhuvan", city: "Kathmandu", country: "Nepal", lat: 27.6966, lon: 85.3591 },
  { icao: "VCBI", iata: "CMB", name: "Colombo Bandaranaike", city: "Colombo", country: "Sri Lanka", lat: 7.1808, lon: 79.8841 },
  { icao: "VGHS", iata: "DAC", name: "Dhaka Hazrat Shahjalal", city: "Dhaka", country: "Bangladesh", lat: 23.8433, lon: 90.3978 },
  { icao: "OPKC", iata: "KHI", name: "Karachi Jinnah", city: "Karachi", country: "Pakistan", lat: 24.9065, lon: 67.1608 },
  { icao: "OPLA", iata: "LHE", name: "Lahore Allama Iqbal", city: "Lahore", country: "Pakistan", lat: 31.5216, lon: 74.4036 },
  { icao: "YSSY", iata: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia", lat: -33.9461, lon: 151.1772 },
  { icao: "YMML", iata: "MEL", name: "Melbourne", city: "Melbourne", country: "Australia", lat: -37.669, lon: 144.841 },
  { icao: "YBBN", iata: "BNE", name: "Brisbane", city: "Brisbane", country: "Australia", lat: -27.3942, lon: 153.1218 },
  { icao: "YPPH", iata: "PER", name: "Perth", city: "Perth", country: "Australia", lat: -31.9403, lon: 115.9669 },
  { icao: "NZAA", iata: "AKL", name: "Auckland", city: "Auckland", country: "New Zealand", lat: -37.0082, lon: 174.785 },
  { icao: "HECA", iata: "CAI", name: "Cairo Intl", city: "Cairo", country: "Egypt", lat: 30.1219, lon: 31.4056 },
  { icao: "FACT", iata: "CPT", name: "Cape Town", city: "Cape Town", country: "South Africa", lat: -33.9649, lon: 18.6017 },
  { icao: "FAOR", iata: "JNB", name: "Johannesburg O.R. Tambo", city: "Johannesburg", country: "South Africa", lat: -26.1392, lon: 28.246 },
  { icao: "GMMN", iata: "CMN", name: "Casablanca Mohammed V", city: "Casablanca", country: "Morocco", lat: 33.3675, lon: -7.59 },
  { icao: "HKJK", iata: "NBO", name: "Nairobi Jomo Kenyatta", city: "Nairobi", country: "Kenya", lat: -1.3192, lon: 36.9278 },
  { icao: "HAAB", iata: "ADD", name: "Addis Ababa Bole", city: "Addis Ababa", country: "Ethiopia", lat: 8.9779, lon: 38.7993 },
  { icao: "DNMM", iata: "LOS", name: "Lagos Murtala Muhammed", city: "Lagos", country: "Nigeria", lat: 6.5774, lon: 3.3212 },
  { icao: "DGAA", iata: "ACC", name: "Accra Kotoka", city: "Accra", country: "Ghana", lat: 5.6052, lon: -0.1668 },
  { icao: "DAAG", iata: "ALG", name: "Algiers Houari Boumediene", city: "Algiers", country: "Algeria", lat: 36.691, lon: 3.2154 },
  { icao: "DTTA", iata: "TUN", name: "Tunis Carthage", city: "Tunis", country: "Tunisia", lat: 36.851, lon: 10.2272 },
  { icao: "CYYZ", iata: "YYZ", name: "Toronto Pearson", city: "Toronto", country: "Canada", lat: 43.6777, lon: -79.6248 },
  { icao: "CYVR", iata: "YVR", name: "Vancouver", city: "Vancouver", country: "Canada", lat: 49.1939, lon: -123.1844 },
  { icao: "CYUL", iata: "YUL", name: "Montreal Trudeau", city: "Montreal", country: "Canada", lat: 45.4706, lon: -73.7408 },
  { icao: "CYYC", iata: "YYC", name: "Calgary", city: "Calgary", country: "Canada", lat: 51.1315, lon: -114.0106 },
  { icao: "MMMX", iata: "MEX", name: "Mexico City", city: "Mexico City", country: "Mexico", lat: 19.4363, lon: -99.0721 },
  { icao: "MMUN", iata: "CUN", name: "Cancun", city: "Cancun", country: "Mexico", lat: 21.0365, lon: -86.8771 },
  { icao: "MMGL", iata: "GDL", name: "Guadalajara", city: "Guadalajara", country: "Mexico", lat: 20.5218, lon: -103.3107 },
  { icao: "SBGR", iata: "GRU", name: "São Paulo Guarulhos", city: "São Paulo", country: "Brazil", lat: -23.4356, lon: -46.4731 },
  { icao: "SBGL", iata: "GIG", name: "Rio de Janeiro Galeão", city: "Rio de Janeiro", country: "Brazil", lat: -22.809, lon: -43.2436 },
  { icao: "SAEZ", iata: "EZE", name: "Buenos Aires Ezeiza", city: "Buenos Aires", country: "Argentina", lat: -34.8222, lon: -58.5358 },
  { icao: "SCEL", iata: "SCL", name: "Santiago", city: "Santiago", country: "Chile", lat: -33.393, lon: -70.7858 },
  { icao: "SKBO", iata: "BOG", name: "Bogotá El Dorado", city: "Bogotá", country: "Colombia", lat: 4.7016, lon: -74.1469 },
  { icao: "SPJC", iata: "LIM", name: "Lima Jorge Chávez", city: "Lima", country: "Peru", lat: -12.0219, lon: -77.1143 },
  { icao: "MPTO", iata: "PTY", name: "Panama City Tocumen", city: "Panama City", country: "Panama", lat: 9.0714, lon: -79.3835 },
  { icao: "MROC", iata: "SJO", name: "San José Juan Santamaría", city: "San José", country: "Costa Rica", lat: 9.9939, lon: -84.2088 },
];
